# Generated by Django 5.2.8 on 2025-11-23 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('documento', models.CharField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=15)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apresentacao', models.TextField()),
                ('quantidade_estoque', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicamentos', to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data_retirada', models.DateField(blank=True, null=True)),
                ('periodo_uso', models.CharField(blank=True, max_length=100)),
                ('data_proxima_retirada', models.DateField(blank=True, null=True)),
                ('data_final', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_de_uso', to='core.medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_do_paciente', to='core.paciente')),
            ],
        ),
    ]
