# Generated by Django 5.2.8 on 2025-11-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrouso',
            name='quantidade',
            field=models.CharField(max_length=50),
        ),
    ]
